In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/jkuypers/Documents/NOVA_IMS/Term_2/Machine_Learning/Project_2/lending-club-loan-data/loan.csv')

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,5550,5550,5550.0,36 months,15.02,192.45,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,2000,2000,2000.0,36 months,17.97,72.28,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,6000,6000,6000.0,36 months,13.56,203.79,C,C1,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,6000,6000,6000.0,36 months,14.47,206.44,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,5500,5500,5500.0,36 months,22.35,211.05,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,28000,28000,28000.0,60 months,11.31,613.13,B,B3,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,11200,11200,11200.0,36 months,8.19,351.95,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,6500,6500,6500.0,36 months,17.97,234.90,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,22000,22000,22000.0,60 months,12.98,500.35,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,3500,3500,3500.0,36 months,16.14,123.30,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,7000,7000,7000.0,36 months,12.98,235.80,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,25000,25000,25000.0,60 months,16.91,620.11,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,16000,16000,16000.0,60 months,20.89,431.87,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,13000,13000,13000.0,60 months,14.47,305.67,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,10000,10000,10000.0,36 months,13.56,339.65,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,13000,13000,13000.0,36 months,14.47,447.29,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,9600,9600,9600.0,36 months,23.40,373.62,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,3500,3500,3500.0,36 months,20.89,131.67,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,16000,16000,16000.0,60 months,26.31,481.99,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,15000,15000,14975.0,60 months,14.47,352.69,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,13000,13000,13000.0,36 months,23.40,505.95,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,23000,23000,23000.0,60 months,20.89,620.81,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,8000,8000,8000.0,36 months,23.40,311.35,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,32075,32075,32075.0,60 months,11.80,710.26,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260638,NaN,NaN,30000,30000,30000.0,36 months,21.45,1137.20,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260639,NaN,NaN,21000,21000,21000.0,36 months,17.09,749.65,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260640,NaN,NaN,20700,20700,20700.0,60 months,12.62,466.98,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260641,NaN,NaN,15000,15000,15000.0,60 months,30.75,492.24,F,F5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260642,NaN,NaN,32400,32400,32375.0,36 months,20.00,1204.11,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260643,NaN,NaN,10000,10000,10000.0,36 months,9.44,320.05,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260644,NaN,NaN,35000,35000,34725.0,60 months,30.75,1148.55,F,F5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260645,NaN,NaN,20000,20000,20000.0,36 months,13.59,679.58,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260646,NaN,NaN,16000,16000,16000.0,60 months,18.06,406.82,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260647,NaN,NaN,10500,10500,10500.0,36 months,13.59,356.78,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260648,NaN,NaN,32000,32000,32000.0,60 months,28.72,1010.30,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260649,NaN,NaN,35000,35000,35000.0,36 months,7.97,1096.29,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260650,NaN,NaN,10000,10000,10000.0,60 months,28.72,315.72,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260651,NaN,NaN,35000,35000,35000.0,60 months,17.09,871.54,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260652,NaN,NaN,25000,25000,25000.0,60 months,30.65,818.85,F,F4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260653,NaN,NaN,15000,15000,15000.0,36 months,10.91,490.45,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260654,NaN,NaN,30000,30000,30000.0,60 months,17.09,747.03,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260655,NaN,NaN,18000,18000,18000.0,60 months,30.65,589.57,F,F4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260656,NaN,NaN,17950,17950,17950.0,60 months,30.17,582.62,F,F3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260657,NaN,NaN,19000,19000,19000.0,60 months,14.08,442.89,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260658,NaN,NaN,15000,15000,15000.0,60 months,16.02,364.94,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260659,NaN,NaN,3500,3500,3500.0,36 months,10.91,114.44,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260660,NaN,NaN,10000,10000,10000.0,36 months,12.62,335.12,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260661,NaN,NaN,21000,21000,21000.0,60 months,30.94,691.60,G,G4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260662,NaN,NaN,30000,30000,30000.0,60 months,30.75,984.47,F,F5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260663,NaN,NaN,12000,12000,12000.0,60 months,14.08,279.72,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260664,NaN,NaN,12000,12000,12000.0,60 months,25.82,358.01,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260665,NaN,NaN,10000,10000,10000.0,36 months,11.99,332.10,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260666,NaN,NaN,12000,12000,12000.0,60 months,21.45,327.69,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260667,NaN,NaN,16550,16550,16550.0,60 months,21.45,451.94,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=145)

In [5]:
#df = df.dropna(axis=1, how='all')

In [6]:
df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=145)

#### Removing NaN

In [7]:
# remove columns with more than 95% of missing values

df = df.loc[:, df.isna().mean() < .95]

In [8]:
df.columns

Index(['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length',
       ...
       'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens',
       'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'disbursement_method',
       'debt_settlement_flag'],
      dtype='object', length=111)

In [9]:
df

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,...,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,N,Cash,N
1,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,...,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,N,Cash,N
2,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,...,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,N,Cash,N
3,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,...,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,N,Cash,N
4,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,...,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,N,Cash,N
5,5550,5550,5550.0,36 months,15.02,192.45,C,C3,Director COE,10+ years,...,60.0,0.0,0.0,831687.0,185378.0,65900.0,203159.0,N,Cash,N
6,2000,2000,2000.0,36 months,17.97,72.28,D,D1,Account Manager,4 years,...,NaN,0.0,0.0,854.0,854.0,0.0,0.0,N,Cash,N
7,6000,6000,6000.0,36 months,13.56,203.79,C,C1,Assistant Director,10+ years,...,85.7,0.0,0.0,117242.0,91535.0,33100.0,61742.0,N,DirectPay,N
8,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Legal Assistant III,10+ years,...,60.0,0.0,0.0,57426.0,41882.0,21500.0,34626.0,N,Cash,N
9,6000,6000,6000.0,36 months,14.47,206.44,C,C2,NaN,< 1 year,...,26.3,0.0,0.0,477390.0,105911.0,98300.0,89600.0,N,Cash,N
10,5500,5500,5500.0,36 months,22.35,211.05,D,D5,NaN,< 1 year,...,100.0,0.0,0.0,243452.0,18185.0,4800.0,15649.0,N,Cash,N
11,28000,28000,28000.0,60 months,11.31,613.13,B,B3,Consultant,2 years,...,37.5,0.0,0.0,259435.0,65636.0,100400.0,17535.0,N,DirectPay,N
12,11200,11200,11200.0,36 months,8.19,351.95,A,A4,Job Coach Supervisor,10+ years,...,20.0,0.0,0.0,345654.0,78795.0,34900.0,114578.0,N,Cash,N
13,6500,6500,6500.0,36 months,17.97,234.90,D,D1,Quality Field Engineer,4 years,...,20.0,0.0,0.0,169160.0,116747.0,12300.0,129860.0,N,Cash,N
14,22000,22000,22000.0,60 months,12.98,500.35,B,B5,Teller,10+ years,...,0.0,0.0,0.0,71932.0,22337.0,27200.0,38535.0,N,Cash,N
15,3500,3500,3500.0,36 months,16.14,123.30,C,C4,respritory therapist,10+ years,...,50.0,0.0,0.0,42328.0,16085.0,8000.0,27028.0,N,Cash,N
16,7000,7000,7000.0,36 months,12.98,235.80,B,B5,Worship Director,4 years,...,0.0,0.0,0.0,214624.0,76709.0,7200.0,96826.0,N,Cash,N
17,25000,25000,25000.0,60 months,16.91,620.11,C,C5,Processor,10+ years,...,100.0,0.0,0.0,92334.0,3044.0,1000.0,0.0,N,Cash,N
18,16000,16000,16000.0,60 months,20.89,431.87,D,D4,Neonatal Nurse Practitioner,4 years,...,100.0,0.0,0.0,444217.0,266754.0,13500.0,239338.0,N,Cash,N
19,13000,13000,13000.0,60 months,14.47,305.67,C,C2,Stationary Engineer,10+ years,...,33.3,0.0,0.0,176598.0,50920.0,26700.0,50898.0,N,Cash,N
20,10000,10000,10000.0,36 months,13.56,339.65,C,C1,NaN,< 1 year,...,80.0,1.0,0.0,48052.0,45972.0,11500.0,34852.0,N,Cash,N
21,13000,13000,13000.0,36 months,14.47,447.29,C,C2,Exhibits director,10+ years,...,75.0,0.0,0.0,41150.0,13878.0,13900.0,1000.0,N,Cash,N
22,9600,9600,9600.0,36 months,23.40,373.62,E,E1,driver coordinator,9 years,...,85.7,0.0,0.0,68902.0,24165.0,7600.0,40402.0,N,Cash,N
23,3500,3500,3500.0,36 months,20.89,131.67,D,D4,gas attendant,10+ years,...,0.0,0.0,0.0,217000.0,26902.0,5000.0,25000.0,N,Cash,N
24,16000,16000,16000.0,60 months,26.31,481.99,E,E4,Financial Relationship Associate,< 1 year,...,55.6,0.0,0.0,45709.0,29869.0,13900.0,10809.0,N,Cash,N
25,15000,15000,14975.0,60 months,14.47,352.69,C,C2,NaN,NaN,...,50.0,0.0,0.0,118790.0,24507.0,9900.0,14490.0,N,Cash,N
26,13000,13000,13000.0,36 months,23.40,505.95,E,E1,Sale Representative,2 years,...,66.7,0.0,0.0,137276.0,87876.0,58600.0,74676.0,N,Cash,N
27,23000,23000,23000.0,60 months,20.89,620.81,D,D4,Operator,5 years,...,0.0,0.0,0.0,7500.0,976.0,3300.0,0.0,N,Cash,N
28,8000,8000,8000.0,36 months,23.40,311.35,E,E1,Manager,10+ years,...,100.0,1.0,0.0,199744.0,31078.0,2300.0,32206.0,N,Cash,N
29,32075,32075,32075.0,60 months,11.80,710.26,B,B4,Nursing Supervisor,10+ years,...,50.0,0.0,0.0,360433.0,56635.0,20000.0,80125.0,N,Cash,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260638,30000,30000,30000.0,36 months,21.45,1137.20,D,D5,Cath lab tech,10+ years,...,33.3,0.0,0.0,247780.0,74697.0,14500.0,73836.0,N,Cash,N
2260639,21000,21000,21000.0,36 months,17.09,749.65,D,D1,Supervisor,10+ years,...,25.0,1.0,0.0,275041.0,72844.0,30600.0,67152.0,N,Cash,N
2260640,20700,20700,20700.0,60 months,12.62,466.98,C,C1,Dental Assistant,10+ years,...,50.0,1.0,0.0,82200.0,33323.0,56500.0,16500.0,N,Cash,N
2260641,15000,15000,15000.0,60 months,30.75,492.24,F,F5,Corporate Recruiter,2 years,...,0.0,1.0,0.0,74909.0,67331.0,14700.0,57909.0,N,Cash,N
2260642,32400,32400,32375.0,36 months,20.00,1204.11,D,D4,SHIPPING MANGER,3 years,...,75.0,1.0,0.0,42367.0,25360.0,19500.0,17367.0,N,Cash,N
2260643,10000,10000,10000.0,36 months,9.44,320.05,B,B1,Acft mechanic,10+ years,...,100.0,0.0,0.0,241052.0,88097.0,16800.0,79352.0,N,Cash,N
2260644,35000,35000,34725.0,60 months,30.75,1148.55,F,F5,Desktop Support Technician,3 years,...,100.0,0.0,0.0,344978.0,56295.0,16400.0,49578.0,N,Cash,N
2260645,20000,20000,20000.0,36 months,13.59,679.58,C,C2,graphic designer,7 years,...,14.3,1.0,0.0,303325.0,15888.0,15100.0,10225.0,N,Cash,N
2260646,16000,16000,16000.0,60 months,18.06,406.82,D,D2,Head Chef,< 1 year,...,33.3,0.0,0.0,308758.0,5962.0,4300.0,20175.0,N,Cash,N
2260647,10500,10500,10500.0,36 months,13.59,356.78,C,C2,NaN,NaN,...,66.7,0.0,0.0,39577.0,28685.0,7200.0,28477.0,N,Cash,N
2260648,32000,32000,32000.0,60 months,28.72,1010.30,F,F1,NaN,NaN,...,0.0,0.0,0.0,30800.0,12194.0,23300.0,7500.0,N,Cash,N
2260649,35000,35000,35000.0,36 months,7.97,1096.29,A,A5,Administrative Assistant,3 years,...,0.0,0.0,0.0,666815.0,103095.0,50200.0,96215.0,N,Cash,N
2260650,10000,10000,10000.0,60 months,28.72,315.72,F,F1,Content Review,1 year,...,66.7,0.0,0.0,41623.0,35073.0,4000.0,32623.0,N,Cash,N
2260651,35000,35000,35000.0,60 months,17.09,871.54,D,D1,Office Manager,< 1 year,...,100.0,0.0,0.0,396635.0,40518.0,15000.0,31500.0,N,Cash,N
2260652,25000,25000,25000.0,60 months,30.65,818.85,F,F4,NaN,NaN,...,0.0,0.0,0.0,66614.0,25299.0,38200.0,21532.0,N,Cash,N
2260653,15000,15000,15000.0,36 months,10.91,490.45,B,B4,NaN,NaN,...,33.3,0.0,0.0,51991.0,32926.0,6800.0,38691.0,N,Cash,N
2260654,30000,30000,30000.0,60 months,17.09,747.03,D,D1,Senior Manager,2 years,...,33.3,0.0,0.0,231009.0,196622.0,49300.0,168609.0,N,Cash,N
2260655,18000,18000,18000.0,60 months,30.65,589.57,F,F4,Package Delivery Driver,10+ years,...,50.0,0.0,0.0,338546.0,18113.0,13800.0,7058.0,N,Cash,N
2260656,17950,17950,17950.0,60 months,30.17,582.62,F,F3,Head Custodian,10+ years,...,0.0,1.0,0.0,203667.0,36652.0,4000.0,63002.0,N,Cash,N
2260657,19000,19000,19000.0,60 months,14.08,442.89,C,C3,NaN,NaN,...,50.0,0.0,0.0,80140.0,44910.0,8000.0,70940.0,N,Cash,N
2260658,15000,15000,15000.0,60 months,16.02,364.94,C,C5,Instructional Designer,< 1 year,...,0.0,0.0,0.0,267274.0,239081.0,22900.0,239074.0,N,Cash,N
2260659,3500,3500,3500.0,36 months,10.91,114.44,B,B4,NaN,NaN,...,50.0,0.0,0.0,69600.0,8571.0,4400.0,10000.0,N,Cash,N
2260660,10000,10000,10000.0,36 months,12.62,335.12,C,C1,Administrator,5 years,...,75.0,0.0,0.0,13300.0,11695.0,13300.0,0.0,N,Cash,N
2260661,21000,21000,21000.0,60 months,30.94,691.60,G,G4,NaN,NaN,...,50.0,0.0,0.0,328405.0,68445.0,1300.0,57142.0,N,Cash,N
2260662,30000,30000,30000.0,60 months,30.75,984.47,F,F5,Sales,6 years,...,50.0,0.0,0.0,201286.0,68680.0,16500.0,64086.0,N,Cash,N
2260663,12000,12000,12000.0,60 months,14.08,279.72,C,C3,house keeper,10+ years,...,66.7,0.0,0.0,73948.0,45212.0,6200.0,49448.0,N,Cash,N
2260664,12000,12000,12000.0,60 months,25.82,358.01,E,E4,Skilled Labor,< 1 year,...,50.0,0.0,0.0,382275.0,12928.0,11400.0,12125.0,N,Cash,N
2260665,10000,10000,10000.0,36 months,11.99,332.10,B,B5,Teacher,10+ years,...,100.0,0.0,0.0,203417.0,36448.0,2000.0,29317.0,N,Cash,N
2260666,12000,12000,12000.0,60 months,21.45,327.69,D,D5,NaN,NaN,...,0.0,0.0,0.0,118975.0,65238.0,22000.0,81975.0,N,Cash,N
2260667,16550,16550,16550.0,60 months,21.45,451.94,D,D5,BABYSITTER,3 years,...,20.0,0.0,0.0,50700.0,25760.0,19500.0,0.0,N,Cash,N

In [10]:
# remove rows with more than 100 missing values
df = df.dropna(axis=0, thresh=100)

In [11]:
#see here that almost all rows have at least one missing value, some of which are categorical and difficult ti impute
df.loc[:, df.isna().any()]

,emp_title,emp_length,desc,title,zip_code,dti,mths_since_last_delinq,mths_since_last_record,revol_util,last_pymnt_d,...,bc_open_to_buy,bc_util,mo_sin_old_il_acct,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_tl_120dpd_2m,pct_tl_nvr_dlq,percent_bc_gt_75
0,Chef,10+ years,NaN,Debt consolidation,109xx,18.24,NaN,45.0,10.3,Feb-2019,...,34360.0,5.9,140.0,1.0,NaN,2.0,NaN,0.0,100.0,0.0
1,Postmaster,10+ years,NaN,Debt consolidation,713xx,26.52,71.0,75.0,24.2,Feb-2019,...,13761.0,8.3,163.0,4.0,NaN,4.0,NaN,0.0,95.0,0.0
2,Administrative,6 years,NaN,Debt consolidation,490xx,10.51,NaN,NaN,19.1,Feb-2019,...,13800.0,0.0,87.0,77.0,NaN,14.0,NaN,0.0,100.0,0.0
3,IT Supervisor,10+ years,NaN,Debt consolidation,985xx,16.74,NaN,NaN,78.1,Feb-2019,...,1239.0,75.2,62.0,64.0,NaN,5.0,NaN,0.0,100.0,100.0
4,Mechanic,10+ years,NaN,Debt consolidation,212xx,26.35,NaN,NaN,3.6,Feb-2019,...,8471.0,8.9,53.0,2.0,NaN,13.0,NaN,0.0,92.3,0.0
5,Director COE,10+ years,NaN,Credit card refinancing,461xx,37.94,NaN,NaN,48.1,Feb-2019,...,23746.0,64.0,195.0,20.0,NaN,3.0,NaN,0.0,100.0,60.0
7,Assistant Director,10+ years,NaN,Credit card refinancing,460xx,30.10,NaN,NaN,69.3,Feb-2019,...,3034.0,90.8,169.0,14.0,NaN,13.0,NaN,0.0,100.0,85.7
8,Legal Assistant III,10+ years,NaN,Debt consolidation,327xx,21.16,32.0,NaN,35.2,Feb-2019,...,13786.0,35.9,145.0,6.0,33.0,2.0,32.0,0.0,78.9,60.0
9,NaN,< 1 year,NaN,Debt consolidation,068xx,17.43,17.0,NaN,49.8,Feb-2019,...,38683.0,60.6,166.0,4.0,NaN,4.0,17.0,0.0,100.0,26.3
10,NaN,< 1 year,NaN,Credit card refinancing,711xx,15.94,22.0,NaN,94.4,Feb-2019,...,271.0,94.4,139.0,5.0,22.0,4.0,22.0,0.0,84.6,100.0
11,Consultant,2 years,NaN,Credit card refinancing,300xx,22.01,NaN,NaN,55.9,Feb-2019,...,44248.0,55.9,180.0,6.0,NaN,6.0,NaN,0.0,100.0,37.5
12,Job Coach Supervisor,10+ years,NaN,Credit card refinancing,840xx,23.60,NaN,NaN,16.6,Feb-2019,...,26289.0,24.7,170.0,65.0,NaN,1.0,NaN,0.0,100.0,20.0
13,Quality Field Engineer,4 years,NaN,Debt consolidation,278xx,28.78,6.0,NaN,60.4,Feb-2019,...,4578.0,62.8,122.0,13.0,NaN,4.0,NaN,0.0,90.2,20.0
14,Teller,10+ years,NaN,Debt consolidation,413xx,11.19,NaN,NaN,0.5,Feb-2019,...,27197.0,0.0,162.0,4.0,NaN,15.0,NaN,0.0,100.0,0.0
15,respritory therapist,10+ years,NaN,Debt consolidation,604xx,13.63,43.0,NaN,58.5,Feb-2019,...,4127.0,48.4,144.0,7.0,NaN,7.0,117.0,0.0,76.0,50.0
16,Worship Director,4 years,NaN,Home buying,436xx,15.20,38.0,NaN,7.2,Feb-2019,...,7200.0,0.0,182.0,26.0,NaN,10.0,NaN,0.0,80.0,0.0
17,Processor,10+ years,NaN,Debt consolidation,453xx,6.26,NaN,NaN,54.4,Feb-2019,...,0.0,104.4,90.0,84.0,NaN,NaN,NaN,0.0,100.0,100.0
18,Neonatal Nurse Practitioner,4 years,NaN,Credit card refinancing,720xx,27.57,8.0,NaN,82.2,Feb-2019,...,430.0,96.8,136.0,12.0,48.0,4.0,8.0,0.0,86.5,100.0
19,Stationary Engineer,10+ years,NaN,Debt consolidation,741xx,26.16,NaN,NaN,58.2,Feb-2019,...,11149.0,58.2,159.0,81.0,NaN,5.0,NaN,0.0,100.0,33.3
20,NaN,< 1 year,NaN,Credit card refinancing,937xx,10.62,30.0,100.0,74.0,Feb-2019,...,1777.0,84.5,168.0,7.0,35.0,5.0,30.0,0.0,77.8,80.0
21,Exhibits director,10+ years,NaN,Credit card refinancing,611xx,10.58,NaN,NaN,82.2,Feb-2019,...,3024.0,78.2,122.0,14.0,NaN,14.0,NaN,0.0,100.0,75.0
22,driver coordinator,9 years,NaN,Credit card refinancing,265xx,23.01,16.0,NaN,37.5,Feb-2019,...,232.0,96.9,183.0,27.0,NaN,15.0,30.0,0.0,90.0,85.7
23,gas attendant,10+ years,NaN,Car financing,078xx,9.09,24.0,NaN,33.5,Feb-2019,...,3683.0,26.3,150.0,8.0,48.0,1.0,48.0,0.0,38.9,0.0
24,Financial Relationship Associate,< 1 year,NaN,Credit card refinancing,290xx,33.62,NaN,NaN,65.5,Feb-2019,...,4596.0,66.9,29.0,2.0,NaN,3.0,NaN,0.0,100.0,55.6
25,NaN,NaN,NaN,Debt consolidation,756xx,41.60,NaN,NaN,37.2,Feb-2019,...,2545.0,74.3,149.0,31.0,NaN,NaN,NaN,0.0,100.0,50.0
26,Sale Representative,2 years,NaN,Other,191xx,39.73,NaN,NaN,83.1,Feb-2019,...,9503.0,83.8,131.0,16.0,NaN,10.0,NaN,0.0,100.0,66.7
27,Operator,5 years,NaN,Debt consolidation,672xx,0.52,NaN,NaN,13.0,Feb-2019,...,3300.0,0.0,237.0,10.0,NaN,9.0,NaN,0.0,100.0,0.0
28,Manager,10+ years,NaN,Debt consolidation,357xx,33.24,NaN,107.0,81.3,Feb-2019,...,126.0,94.5,148.0,51.0,NaN,7.0,NaN,0.0,100.0,100.0
29,Nursing Supervisor,10+ years,NaN,Credit card refinancing,231xx,22.21,NaN,NaN,32.0,Feb-2019,...,10446.0,47.8,160.0,27.0,NaN,14.0,NaN,0.0,100.0,50.0
30,NaN,< 1 year,NaN,Debt consolidation,180xx,19.23,NaN,NaN,55.5,Feb-2019,...,16601.0,54.9,4.0,10.0,NaN,4.0,NaN,0.0,100.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260637,technician,3 years,NaN,Debt consolidation,917xx,20.70,18.0,NaN,36.1,Feb-2019,...,11238.0,36.1,286.0,22.0,18.0,8.0,18.0,0.0,81.8,33.3
2260638,Cath lab tech,10+ years,NaN,Debt consolidation,605xx,25.76,69.0,NaN,55.9,Jul-2018,...,5412.0,62.7,238.0,15.0,NaN,5.0,NaN,0.0,100.0,33.3
2260639,Supervisor,10+ years,NaN,Debt consolidation,233xx,25.47,25.0,60.0,42.0,Nov-2018,...,3825.0,43.0,128.0,12.0,NaN,4.0,NaN,NaN,77.0,25.0
2260640,Dental Assistant,10+ years,NaN,Debt consolidation,461xx,27.05,73.0,88.0,33.0,Sep-2018,...,14125.0,35.0,166.0,9.0,NaN,12.0,NaN,NaN,94.0,50.0
2260641,Corporate Recruiter,2 years,NaN,Debt consolidation,852xx,21.25,48.0,46.0,17.2,Feb-2018,...,12023.0,18.2,166.0,6.0,NaN,1.0,NaN,0.0,73.9,0.0
2260642,SHIPPING MANGER,3 years,NaN,Debt consolidation,113xx,13.37,NaN,73.0,57.0,Feb-2019,...,4875.0,70.0,130.0,2.0,NaN,2.0,NaN,NaN,100.0,75.0
2260643,Acft mechanic,10+ years,NaN,Debt consolidation,363xx,28.59,9.0,NaN,91.0,Nov-2018,...,5600.0,99.0,226.0,34.0,34.0,7.0,31.0,NaN,86.0,100.0
2260644,Desktop Support Technician,3 years,NaN,Other,958xx,19.07,NaN,NaN,98.2,Feb-2019,...,296.0,98.2,113.0,19.0,NaN,1.0,NaN,0.0,100.0,100.0
2260645,graphic designer,7 years,NaN,Credit card refinancing,330xx,14.57,NaN,93.0,38.0,Feb-2019,...,9196.0,39.1,66.0,17.0,NaN,16.0,NaN,0.0,100.0,14.3
2260646,Head Chef,< 1 year,NaN,Debt consolidation,294xx,8.28,8.0,NaN,24.0,Nov-2018,...,2907.0,32.4,60.0,8.0,27.0,8.0,8.0,0.0,58.8,33.3
2260647,NaN,NaN,NaN,Debt consolidation,633xx,34.00,43.0,NaN,54.0,Feb-2019,...,4275.0,40.6,164.0,11.0,76.0,7.0,76.0,0.0,78.6,66.7
2260648,NaN,NaN,NaN,Debt consolidation,606xx,9.31,3.0,NaN,24.2,Feb-2019,...,17657.0,24.2,128.0,547.0,NaN,NaN,NaN,0.0,66.7,0.0
2260649,Administrative Assistant,3 years,NaN,Debt consolidation,117xx,66.19,35.0,NaN,34.7,Feb-2019,...,36776.0,26.7,120.0,1.0,54.0,6.0,47.0,0.0,80.0,0.0
2260650,Content Review,1 year,NaN,Business,945xx,16.08,NaN,NaN,59.0,Jan-2019,...,467.0,88.3,46.0,20.0,NaN,9.0,NaN,0.0,100.0,66.7
2260651,Office Manager,< 1 year,NaN,Debt consolidation,601xx,66.03,NaN,NaN,96.5,Feb-2019,...,525.0,96.5,63.0,53.0,NaN,17.0,NaN,0.0,100.0,100.0
2260652,NaN,NaN,NaN,Debt consolidation,841xx,12.81,4.0,NaN,11.6,Oct-2017,...,33679.0,13.1,120.0,6.0,50.0,12.0,50.0,0.0,88.0,0.0
2260653,NaN,NaN,NaN,Debt consolidation,071xx,18.24,2.0,NaN,44.7,Feb-2019,...,2467.0,63.7,243.0,37.0,21.0,9.0,2.0,0.0,83.3,33.3
2260654,Senior Manager,2 years,NaN,Debt consolidation,112xx,23.22,46.0,NaN,30.8,Jun-2018,...,31294.0,36.5,189.0,5.0,NaN,2.0,46.0,0.0,54.9,33.3
2260655,Package Delivery Driver,10+ years,NaN,Debt consolidation,799xx,8.08,38.0,NaN,45.1,Aug-2018,...,7083.0,48.7,156.0,5.0,38.0,4.0,38.0,0.0,93.3,50.0
2260656,Head Custodian,10+ years,NaN,Debt consolidation,600xx,33.24,NaN,80.0,35.9,Apr-2018,...,1587.0,60.3,109.0,16.0,NaN,0.0,NaN,0.0,100.0,0.0
2260657,NaN,NaN,NaN,Major purchase,660xx,48.22,13.0,NaN,42.2,Feb-2019,...,5222.0,34.7,143.0,18.0,NaN,18.0,NaN,0.0,91.7,50.0
2260658,Instructional Designer,< 1 year,NaN,Debt consolidation,119xx,14.66,36.0,NaN,24.8,Mar-2018,...,17477.0,23.7,191.0,2.0,36.0,0.0,36.0,0.0,89.0,0.0
2260659,NaN,NaN,NaN,Debt consolidation,770xx,24.80,23.0,NaN,36.5,Feb-2019,...,1034.0,76.5,63.0,8.0,23.0,3.0,23.0,0.0,89.3,50.0
2260660,Administrator,5 years,NaN,Credit card refinancing,770xx,4.41,29.0,NaN,87.9,Feb-2019,...,1605.0,87.9,NaN,6.0,29.0,15.0,29.0,0.0,80.0,75.0
2260661,NaN,NaN,NaN,Medical expenses,312xx,26.44,7.0,NaN,95.4,Feb-2019,...,675.0,48.1,123.0,67.0,7.0,0.0,7.0,0.0,86.2,50.0
2260662,Sales,6 years,NaN,Debt consolidation,338xx,22.13,NaN,NaN,66.9,Feb-2019,...,6942.0,57.9,37.0,26.0,NaN,4.0,NaN,0.0,100.0,50.0
2260663,house keeper,10+ years,NaN,Debt consolidation,054xx,20.88,NaN,NaN,39.2,Feb-2019,...,1807.0,70.9,157.0,9.0,NaN,9.0,NaN,0.0,100.0,66.7
2260664,Skilled Labor,< 1 year,NaN,Debt consolidation,971xx,19.28,13.0,NaN,20.2,Aug-2018,...,9162.0,19.6,163.0,141.0,46.0,0.0,17.0,0.0,76.9,50.0
2260665,Teacher,10+ years,NaN,Debt consolidation,603xx,12.96,NaN,NaN,70.9,Feb-2019,...,136.0,93.2,134.0,111.0,NaN,3.0,NaN,0.0,100.0,100.0
2260666,NaN,NaN,NaN,Debt consolidation,996xx,30.82,7.0,NaN,34.9,Feb-2019,...,18789.0,14.6,170.0,16.0,9.0,5.0,7.0,0.0,88.2,0.0

In [12]:
#Decide to drop all columns with missing values - have 82 columns left
df = df.dropna(axis=1)

In [13]:
df.dtypes

loan_amnt                       int64
funded_amnt                     int64
funded_amnt_inv               float64
term                           object
int_rate                      float64
installment                   float64
grade                          object
sub_grade                      object
home_ownership                 object
annual_inc                    float64
verification_status            object
issue_d                        object
loan_status                    object
pymnt_plan                     object
purpose                        object
addr_state                     object
delinq_2yrs                   float64
earliest_cr_line               object
inq_last_6mths                float64
open_acc                      float64
pub_rec                       float64
revol_bal                       int64
total_acc                     float64
initial_list_status            object
out_prncp                     float64
out_prncp_inv                 float64
total_pymnt                   float64
total_pymnt_inv               float64
total_rec_prncp               float64
total_rec_int                 float64
                               ...
acc_open_past_24mths          float64
avg_cur_bal                   float64
chargeoff_within_12_mths      float64
delinq_amnt                   float64
mo_sin_old_rev_tl_op          float64
mo_sin_rcnt_rev_tl_op         float64
mo_sin_rcnt_tl                float64
mort_acc                      float64
num_accts_ever_120_pd         float64
num_actv_bc_tl                float64
num_actv_rev_tl               float64
num_bc_sats                   float64
num_bc_tl                     float64
num_il_tl                     float64
num_op_rev_tl                 float64
num_rev_accts                 float64
num_rev_tl_bal_gt_0           float64
num_sats                      float64
num_tl_30dpd                  float64
num_tl_90g_dpd_24m            float64
num_tl_op_past_12m            float64
pub_rec_bankruptcies          float64
tax_liens                     float64
tot_hi_cred_lim               float64
total_bal_ex_mort             float64
total_bc_limit                float64
total_il_high_credit_limit    float64
hardship_flag                  object
disbursement_method            object
debt_settlement_flag           object
Length: 82, dtype: object

In [14]:
# categorising grade (G is lowest and A is highest)
# categorising subgrade (1 is low and 5 is high)


df['grade'] = df['grade'].map({'G':'1', 'F':'2', 'E': '3', 'D':'4', 'C': '5', 'B': '6', 'A':'7'})
df['sub_grade'] = df['sub_grade'].map({'A1':'31', 'A2':'32', 'A3':'33', 'A4':'34', 'A5':'35', 'B1':'26', 'B2':'27', 'B3':'28', 'B4':'29', 'B5':'30', 'C1':'21',
       'C2':'22', 'C3':'23', 'C4':'24', 'C5':'25', 'D1':'16', 'D2':'17', 'D3':'18', 'D4':'19', 'D5':'20', 'E1':'11', 'E2':'12',
       'E3':'13', 'E4':'15', 'E5':'15', 'F1':'6', 'F2':'7', 'F3':'8', 'F4':'9', 'F5':'10', 'G1':'1', 'G2':'2', 'G3':'3',
       'G4':'4', 'G5':'5'})

## we can probably remove the 'grade' column since subgrade holds the same information & more

In [15]:
df

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,home_ownership,annual_inc,...,num_tl_op_past_12m,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,2500,2500,2500.0,36 months,13.56,84.92,5,21,RENT,55000.0,...,3.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,N,Cash,N
1,30000,30000,30000.0,60 months,18.94,777.23,4,17,MORTGAGE,90000.0,...,6.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,N,Cash,N
2,5000,5000,5000.0,36 months,17.97,180.69,4,16,MORTGAGE,59280.0,...,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,N,Cash,N
3,4000,4000,4000.0,36 months,18.94,146.51,4,17,MORTGAGE,92000.0,...,3.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,N,Cash,N
4,30000,30000,30000.0,60 months,16.14,731.78,5,24,MORTGAGE,57250.0,...,5.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,N,Cash,N
5,5550,5550,5550.0,36 months,15.02,192.45,5,23,MORTGAGE,152500.0,...,4.0,0.0,0.0,831687.0,185378.0,65900.0,203159.0,N,Cash,N
7,6000,6000,6000.0,36 months,13.56,203.79,5,21,RENT,65000.0,...,0.0,0.0,0.0,117242.0,91535.0,33100.0,61742.0,N,DirectPay,N
8,5000,5000,5000.0,36 months,17.97,180.69,4,16,MORTGAGE,53580.0,...,6.0,0.0,0.0,57426.0,41882.0,21500.0,34626.0,N,Cash,N
9,6000,6000,6000.0,36 months,14.47,206.44,5,22,OWN,300000.0,...,2.0,0.0,0.0,477390.0,105911.0,98300.0,89600.0,N,Cash,N
10,5500,5500,5500.0,36 months,22.35,211.05,4,20,MORTGAGE,50000.0,...,2.0,0.0,0.0,243452.0,18185.0,4800.0,15649.0,N,Cash,N
11,28000,28000,28000.0,60 months,11.31,613.13,6,28,MORTGAGE,70000.0,...,1.0,0.0,0.0,259435.0,65636.0,100400.0,17535.0,N,DirectPay,N
12,11200,11200,11200.0,36 months,8.19,351.95,7,34,MORTGAGE,65000.0,...,2.0,0.0,0.0,345654.0,78795.0,34900.0,114578.0,N,Cash,N
13,6500,6500,6500.0,36 months,17.97,234.90,4,16,MORTGAGE,154000.0,...,4.0,0.0,0.0,169160.0,116747.0,12300.0,129860.0,N,Cash,N
14,22000,22000,22000.0,60 months,12.98,500.35,6,30,MORTGAGE,65000.0,...,1.0,0.0,0.0,71932.0,22337.0,27200.0,38535.0,N,Cash,N
15,3500,3500,3500.0,36 months,16.14,123.30,5,24,MORTGAGE,80000.0,...,3.0,0.0,0.0,42328.0,16085.0,8000.0,27028.0,N,Cash,N
16,7000,7000,7000.0,36 months,12.98,235.80,6,30,MORTGAGE,102500.0,...,2.0,0.0,0.0,214624.0,76709.0,7200.0,96826.0,N,Cash,N
17,25000,25000,25000.0,60 months,16.91,620.11,5,25,MORTGAGE,23878.0,...,0.0,0.0,0.0,92334.0,3044.0,1000.0,0.0,N,Cash,N
18,16000,16000,16000.0,60 months,20.89,431.87,4,19,MORTGAGE,120000.0,...,2.0,0.0,0.0,444217.0,266754.0,13500.0,239338.0,N,Cash,N
19,13000,13000,13000.0,60 months,14.47,305.67,5,22,MORTGAGE,75000.0,...,1.0,0.0,0.0,176598.0,50920.0,26700.0,50898.0,N,Cash,N
20,10000,10000,10000.0,36 months,13.56,339.65,5,21,MORTGAGE,65000.0,...,2.0,1.0,0.0,48052.0,45972.0,11500.0,34852.0,N,Cash,N
21,13000,13000,13000.0,36 months,14.47,447.29,5,22,MORTGAGE,55000.0,...,0.0,0.0,0.0,41150.0,13878.0,13900.0,1000.0,N,Cash,N
22,9600,9600,9600.0,36 months,23.40,373.62,3,11,RENT,65000.0,...,1.0,0.0,0.0,68902.0,24165.0,7600.0,40402.0,N,Cash,N
23,3500,3500,3500.0,36 months,20.89,131.67,4,19,MORTGAGE,40000.0,...,3.0,0.0,0.0,217000.0,26902.0,5000.0,25000.0,N,Cash,N
24,16000,16000,16000.0,60 months,26.31,481.99,3,15,RENT,33000.0,...,1.0,0.0,0.0,45709.0,29869.0,13900.0,10809.0,N,Cash,N
25,15000,15000,14975.0,60 months,14.47,352.69,5,22,MORTGAGE,30000.0,...,1.0,0.0,0.0,118790.0,24507.0,9900.0,14490.0,N,Cash,N
26,13000,13000,13000.0,36 months,23.40,505.95,3,11,MORTGAGE,90000.0,...,1.0,0.0,0.0,137276.0,87876.0,58600.0,74676.0,N,Cash,N
27,23000,23000,23000.0,60 months,20.89,620.81,4,19,RENT,68107.0,...,3.0,0.0,0.0,7500.0,976.0,3300.0,0.0,N,Cash,N
28,8000,8000,8000.0,36 months,23.40,311.35,3,11,OWN,43000.0,...,2.0,1.0,0.0,199744.0,31078.0,2300.0,32206.0,N,Cash,N
29,32075,32075,32075.0,60 months,11.80,710.26,6,29,MORTGAGE,150000.0,...,2.0,0.0,0.0,360433.0,56635.0,20000.0,80125.0,N,Cash,N
30,12000,12000,12000.0,60 months,13.56,276.49,5,21,MORTGAGE,40000.0,...,3.0,0.0,0.0,50800.0,32462.0,36800.0,9000.0,N,Cash,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260637,23375,23375,23375.0,36 months,21.45,886.07,4,20,RENT,80000.0,...,1.0,0.0,0.0,70622.0,44869.0,17600.0,53022.0,N,Cash,N
2260638,30000,30000,30000.0,36 months,21.45,1137.20,4,20,MORTGAGE,94000.0,...,4.0,0.0,0.0,247780.0,74697.0,14500.0,73836.0,N,Cash,N
2260639,21000,21000,21000.0,36 months,17.09,749.65,4,16,MORTGAGE,77000.0,...,11.0,1.0,0.0,275041.0,72844.0,30600.0,67152.0,N,Cash,N
2260640,20700,20700,20700.0,60 months,12.62,466.98,5,21,OWN,46000.0,...,3.0,1.0,0.0,82200.0,33323.0,56500.0,16500.0,N,Cash,N
2260641,15000,15000,15000.0,60 months,30.75,492.24,2,10,RENT,55000.0,...,3.0,1.0,0.0,74909.0,67331.0,14700.0,57909.0,N,Cash,N
2260642,32400,32400,32375.0,36 months,20.00,1204.11,4,19,OWN,72000.0,...,5.0,1.0,0.0,42367.0,25360.0,19500.0,17367.0,N,Cash,N
2260643,10000,10000,10000.0,36 months,9.44,320.05,6,26,MORTGAGE,103510.0,...,1.0,0.0,0.0,241052.0,88097.0,16800.0,79352.0,N,Cash,N
2260644,35000,35000,34725.0,60 months,30.75,1148.55,2,10,OWN,78960.0,...,2.0,0.0,0.0,344978.0,56295.0,16400.0,49578.0,N,Cash,N
2260645,20000,20000,20000.0,36 months,13.59,679.58,5,22,MORTGAGE,70000.0,...,0.0,1.0,0.0,303325.0,15888.0,15100.0,10225.0,N,Cash,N
2260646,16000,16000,16000.0,60 months,18.06,406.82,4,17,MORTGAGE,50000.0,...,3.0,0.0,0.0,308758.0,5962.0,4300.0,20175.0,N,Cash,N
2260647,10500,10500,10500.0,36 months,13.59,356.78,5,22,OWN,31000.0,...,2.0,0.0,0.0,39577.0,28685.0,7200.0,28477.0,N,Cash,N
2260648,32000,32000,32000.0,60 months,28.72,1010.30,2,6,OWN,33000.0,...,0.0,0.0,0.0,30800.0,12194.0,23300.0,7500.0,N,Cash,N
2260649,35000,35000,35000.0,36 months,7.97,1096.29,7,35,MORTGAGE,40000.0,...,10.0,0.0,0.0,666815.0,103095.0,50200.0,96215.0,N,Cash,N
2260650,10000,10000,10000.0,60 months,28.72,315.72,2,6,RENT,48000.0,...,2.0,0.0,0.0,41623.0,35073.0,4000.0,32623.0,N,Cash,N
2260651,35000,35000,35000.0,60 months,17.09,871.54,4,16,MORTGAGE,20736.0,...,0.0,0.0,0.0,396635.0,40518.0,15000.0,31500.0,N,Cash,N
2260652,25000,25000,25000.0,60 months,30.65,818.85,2,9,RENT,54778.0,...,6.0,0.0,0.0,66614.0,25299.0,38200.0,21532.0,N,Cash,N
2260653,15000,15000,15000.0,36 months,10.91,490.45,6,29,RENT,60000.0,...,0.0,0.0,0.0,51991.0,32926.0,6800.0,38691.0,N,Cash,N
2260654,30000,30000,30000.0,60 months,17.09,747.03,4,16,RENT,80000.0,...,3.0,0.0,0.0,231009.0,196622.0,49300.0,168609.0,N,Cash,N
2260655,18000,18000,18000.0,60 months,30.65,589.57,2,9,MORTGAGE,77000.0,...,5.0,0.0,0.0,338546.0,18113.0,13800.0,7058.0,N,Cash,N
2260656,17950,17950,17950.0,60 months,30.17,582.62,2,8,MORTGAGE,53758.0,...,2.0,1.0,0.0,203667.0,36652.0,4000.0,63002.0,N,Cash,N
2260657,19000,19000,19000.0,60 months,14.08,442.89,5,23,MORTGAGE,49200.0,...,1.0,0.0,0.0,80140.0,44910.0,8000.0,70940.0,N,Cash,N
2260658,15000,15000,15000.0,60 months,16.02,364.94,5,25,RENT,85000.0,...,7.0,0.0,0.0,267274.0,239081.0,22900.0,239074.0,N,Cash,N
2260659,3500,3500,3500.0,36 months,10.91,114.44,6,29,OWN,21000.0,...,1.0,0.0,0.0,69600.0,8571.0,4400.0,10000.0,N,Cash,N
2260660,10000,10000,10000.0,36 months,12.62,335.12,5,21,RENT,65000.0,...,1.0,0.0,0.0,13300.0,11695.0,13300.0,0.0,N,Cash,N
2260661,21000,21000,21000.0,60 months,30.94,691.60,1,4,MORTGAGE,90000.0,...,3.0,0.0,0.0,328405.0,68445.0,1300.0,57142.0,N,Cash,N
2260662,30000,30000,30000.0,60 months,30.75,984.47,2,10,MORTGAGE,100000.0,...,3.0,0.0,0.0,201286.0,68680.0,16500.0,64086.0,N,Cash,N
2260663,12000,12000,12000.0,60 months,14.08,279.72,5,23,MORTGAGE,58000.0,...,3.0,0.0,0.0,73948.0,45212.0,6200.0,49448.0,N,Cash,N
2260664,12000,12000,12000.0,60 months,25.82,358.01,3,15,MORTGAGE,30000.0,...,1.0,0.0,0.0,382275.0,12928.0,11400.0,12125.0,N,Cash,N
2260665,10000,10000,10000.0,36 months,11.99,332.10,6,30,OWN,64000.0,...,1.0,0.0,0.0,203417.0,36448.0,2000.0,29317.0,N,Cash,N
2260666,12000,12000,12000.0,60 months,21.45,327.69,4,20,RENT,60000.0,...,3.0,0.0,0.0,118975.0,65238.0,22000.0,81975.0,N,Cash,N

In [16]:
#convert issue_d to datetime
df['issue_d'] = pd.to_datetime(df.issue_d)

In [17]:
# turn boolean columns to binary
df['debt_settlement_flag'] = df['debt_settlement_flag'].map({'N':'0', 'Y':'1'})

df['initial_list_status'] = df['initial_list_status'].map({'f':'0', 'w':'1'})

df['hardship_flag'] = df['hardship_flag'].map({'N':'0', 'Y':'1'})

df['pymnt_plan'] = df['pymnt_plan'].map({'n':'0', 'y':'1'})

In [18]:
# One Hot Encode categorical values

home_ownership = pd.get_dummies(df['home_ownership'], prefix='home_ownership_', drop_first=False)
df = pd.concat([df, home_ownership], axis=1)
        
verification_status = pd.get_dummies(df['verification_status'], prefix='verification_status_', drop_first=False)
df = pd.concat([df, verification_status], axis=1)

application_type = pd.get_dummies(df['application_type'], prefix='application_type_', drop_first=False)
df = pd.concat([df, application_type], axis=1)

disbursement_method = pd.get_dummies(df['disbursement_method'], prefix='disbursement_method_', drop_first=False)
df = pd.concat([df, disbursement_method], axis=1)

loan_status = pd.get_dummies(df['loan_status'], prefix='loan_status_', drop_first=False)
df = pd.concat([df, loan_status], axis=1)

purpose = pd.get_dummies(df['purpose'], prefix='purpose_', drop_first=False)
df = pd.concat([df, purpose], axis=1)

term = pd.get_dummies(df['term'], prefix='term_', drop_first=False)
df = pd.concat([df, term], axis=1)

addr_state = pd.get_dummies(df['addr_state'], prefix='addr_state_', drop_first=False)
df = pd.concat([df, addr_state], axis=1)

In [19]:
#drop categorical columns - are already to one hot encoded
df = df.drop(['home_ownership','verification_status','application_type','disbursement_method', 'loan_status',
             'purpose', 'term', 'addr_state'], axis=1)

In [20]:
df

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,grade,sub_grade,annual_inc,issue_d,pymnt_plan,...,addr_state__SD,addr_state__TN,addr_state__TX,addr_state__UT,addr_state__VA,addr_state__VT,addr_state__WA,addr_state__WI,addr_state__WV,addr_state__WY
0,2500,2500,2500.0,13.56,84.92,5,21,55000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
1,30000,30000,30000.0,18.94,777.23,4,17,90000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
2,5000,5000,5000.0,17.97,180.69,4,16,59280.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
3,4000,4000,4000.0,18.94,146.51,4,17,92000.0,2018-12-01,0,...,0,0,0,0,0,0,1,0,0,0
4,30000,30000,30000.0,16.14,731.78,5,24,57250.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
5,5550,5550,5550.0,15.02,192.45,5,23,152500.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
7,6000,6000,6000.0,13.56,203.79,5,21,65000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
8,5000,5000,5000.0,17.97,180.69,4,16,53580.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
9,6000,6000,6000.0,14.47,206.44,5,22,300000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
10,5500,5500,5500.0,22.35,211.05,4,20,50000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
11,28000,28000,28000.0,11.31,613.13,6,28,70000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
12,11200,11200,11200.0,8.19,351.95,7,34,65000.0,2018-12-01,0,...,0,0,0,1,0,0,0,0,0,0
13,6500,6500,6500.0,17.97,234.90,4,16,154000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
14,22000,22000,22000.0,12.98,500.35,6,30,65000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
15,3500,3500,3500.0,16.14,123.30,5,24,80000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
16,7000,7000,7000.0,12.98,235.80,6,30,102500.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
17,25000,25000,25000.0,16.91,620.11,5,25,23878.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
18,16000,16000,16000.0,20.89,431.87,4,19,120000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
19,13000,13000,13000.0,14.47,305.67,5,22,75000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
20,10000,10000,10000.0,13.56,339.65,5,21,65000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
21,13000,13000,13000.0,14.47,447.29,5,22,55000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
22,9600,9600,9600.0,23.40,373.62,3,11,65000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,1,0
23,3500,3500,3500.0,20.89,131.67,4,19,40000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
24,16000,16000,16000.0,26.31,481.99,3,15,33000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
25,15000,15000,14975.0,14.47,352.69,5,22,30000.0,2018-12-01,0,...,0,0,1,0,0,0,0,0,0,0
26,13000,13000,13000.0,23.40,505.95,3,11,90000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
27,23000,23000,23000.0,20.89,620.81,4,19,68107.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
28,8000,8000,8000.0,23.40,311.35,3,11,43000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
29,32075,32075,32075.0,11.80,710.26,6,29,150000.0,2018-12-01,0,...,0,0,0,0,1,0,0,0,0,0
30,12000,12000,12000.0,13.56,276.49,5,21,40000.0,2018-12-01,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260637,23375,23375,23375.0,21.45,886.07,4,20,80000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260638,30000,30000,30000.0,21.45,1137.20,4,20,94000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260639,21000,21000,21000.0,17.09,749.65,4,16,77000.0,2017-10-01,0,...,0,0,0,0,1,0,0,0,0,0
2260640,20700,20700,20700.0,12.62,466.98,5,21,46000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260641,15000,15000,15000.0,30.75,492.24,2,10,55000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260642,32400,32400,32375.0,20.00,1204.11,4,19,72000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260643,10000,10000,10000.0,9.44,320.05,6,26,103510.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260644,35000,35000,34725.0,30.75,1148.55,2,10,78960.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260645,20000,20000,20000.0,13.59,679.58,5,22,70000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260646,16000,16000,16000.0,18.06,406.82,4,17,50000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260647,10500,10500,10500.0,13.59,356.78,5,22,31000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260648,32000,32000,32000.0,28.72,1010.30,2,6,33000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260649,35000,35000,35000.0,7.97,1096.29,7,35,40000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260650,10000,10000,10000.0,28.72,315.72,2,6,48000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260651,35000,35000,35000.0,17.09,871.54,4,16,20736.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260652,25000,25000,25000.0,30.65,818.85,2,9,54778.0,2017-10-01,0,...,0,0,0,1,0,0,0,0,0,0
2260653,15000,15000,15000.0,10.91,490.45,6,29,60000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260654,30000,30000,30000.0,17.09,747.03,4,16,80000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260655,18000,18000,18000.0,30.65,589.57,2,9,77000.0,2017-10-01,0,...,0,0,1,0,0,0,0,0,0,0
2260656,17950,17950,17950.0,30.17,582.62,2,8,53758.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260657,19000,19000,19000.0,14.08,442.89,5,23,49200.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260658,15000,15000,15000.0,16.02,364.94,5,25,85000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260659,3500,3500,3500.0,10.91,114.44,6,29,21000.0,2017-10-01,0,...,0,0,1,0,0,0,0,0,0,0
2260660,10000,10000,10000.0,12.62,335.12,5,21,65000.0,2017-10-01,0,...,0,0,1,0,0,0,0,0,0,0
2260661,21000,21000,21000.0,30.94,691.60,1,4,90000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260662,30000,30000,30000.0,30.75,984.47,2,10,100000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260663,12000,12000,12000.0,14.08,279.72,5,23,58000.0,2017-10-01,0,...,0,0,0,0,0,1,0,0,0,0
2260664,12000,12000,12000.0,25.82,358.01,3,15,30000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260665,10000,10000,10000.0,11.99,332.10,6,30,64000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0
2260666,12000,12000,12000.0,21.45,327.69,4,20,60000.0,2017-10-01,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
df.initial_list_status.value_counts()

1    1074327
0     256558
Name: initial_list_status, dtype: int64

In [22]:
#change categorical/object columns to numeric
objects_ = df.select_dtypes(include=['object'])
objects_ = objects_.columns
df[objects_] = df[objects_].apply(pd.to_numeric, errors='coerce')

In [24]:
df.dtypes

loan_amnt                              int64
funded_amnt                            int64
funded_amnt_inv                      float64
int_rate                             float64
installment                          float64
grade                                  int64
sub_grade                              int64
annual_inc                           float64
issue_d                       datetime64[ns]
pymnt_plan                             int64
delinq_2yrs                          float64
earliest_cr_line                     float64
inq_last_6mths                       float64
open_acc                             float64
pub_rec                              float64
revol_bal                              int64
total_acc                            float64
initial_list_status                    int64
out_prncp                            float64
out_prncp_inv                        float64
total_pymnt                          float64
total_pymnt_inv                      float64
total_rec_prncp                      float64
total_rec_int                        float64
total_rec_late_fee                   float64
recoveries                           float64
collection_recovery_fee              float64
last_pymnt_amnt                      float64
collections_12_mths_ex_med           float64
policy_code                            int64
                                   ...
addr_state__ME                         uint8
addr_state__MI                         uint8
addr_state__MN                         uint8
addr_state__MO                         uint8
addr_state__MS                         uint8
addr_state__MT                         uint8
addr_state__NC                         uint8
addr_state__ND                         uint8
addr_state__NE                         uint8
addr_state__NH                         uint8
addr_state__NJ                         uint8
addr_state__NM                         uint8
addr_state__NV                         uint8
addr_state__NY                         uint8
addr_state__OH                         uint8
addr_state__OK                         uint8
addr_state__OR                         uint8
addr_state__PA                         uint8
addr_state__RI                         uint8
addr_state__SC                         uint8
addr_state__SD                         uint8
addr_state__TN                         uint8
addr_state__TX                         uint8
addr_state__UT                         uint8
addr_state__VA                         uint8
addr_state__VT                         uint8
addr_state__WA                         uint8
addr_state__WI                         uint8
addr_state__WV                         uint8
addr_state__WY                         uint8
Length: 159, dtype: object

In [25]:
df.to_csv('cleanedLoanClub.csv')